from django.conf.urls import include, url
import redirect.views

urlpatterns = [
    url(r'^$', redirect.views.WildcardRedirectView.as_view(),
        {'redirect_to': 'home'},
        name='home'),

    url(r'^admin/.*', redirect.views.PathRedirectView.as_view(),
        name='admin'),
    url(r'^lti/.*', redirect.views.PathRedirectView.as_view(),
        name='lti'),

    url(r'^auth/login/$', redirect.views.PathRedirectView.as_view(),
        name='auth-login'),
    url(r'^logout/$', redirect.views.PathRedirectView.as_view(),
        name='logout'),

    url(r'^share/?$', redirect.views.ShareView.as_view(),
        name='share'),
    url(r'^help/?$', redirect.views.PathRedirectView.as_view(),
        name='help'),
    url(r'^terms/?$', redirect.views.PathRedirectView.as_view(),
        name='terms'),

    url(r'^artwork/studio/$', redirect.views.PathRedirectView.as_view(),
        name='artwork-studio'),
    url(r'^a/?$', redirect.views.ObjectRedirectView.as_view(),
        {'model': 'artwork.artwork'},
        name='artwork-shared'),
    url(r'^a/score/$', redirect.views.ObjectRedirectView.as_view(),
        {'model': 'artwork.artwork'},
        name='artwork-shared-score'),
    url(r'^a/list/$', redirect.views.PathRedirectView.as_view(),
        name='artwork-list'),
    url(r'^a/by/(?P<pk>\d+)/(?:(?P<shared>\d+)/)?$', redirect.views.ObjectRedirectView.as_view(),
        {'model': 'lti.user', 'shared': 1},
        name='artwork-author-list'),
    url(r'^a/by/(?P<pk>\d+)/(?:(?P<shared>\d+)/)?code.zip$', redirect.views.ObjectRedirectView.as_view(),
        {'model': 'lti.user', 'shared': 1},
        name='artwork-author-list-zip'),

    url(r'^s(?P<pk>\d+).pde$', redirect.views.ObjectRedirectView.as_view(),
        {'model': 'submissions.submission'},
        name='artwork-shared-code'),
    url(r'^artwork/new/$', redirect.views.PathRedirectView.as_view(),
        name='artwork-add'),
    url(r'^artwork/edit/(?P<pk>\d+)/$', redirect.views.ObjectRedirectView.as_view(),
        {'model': 'artwork.artwork'},
        name='artwork-edit'),
    url(r'^artwork/clone/(?P<pk>\d+)/$', redirect.views.ObjectRedirectView.as_view(),
        {'model': 'artwork.artwork'},
        name='artwork-clone'),
    url(r'^artwork/delete/(?P<pk>\d+)/$', redirect.views.ObjectRedirectView.as_view(),
        {'model': 'artwork.artwork'},
        name='artwork-delete'),
    url(r'^a/(?P<pk>\d+)/$', redirect.views.ObjectRedirectView.as_view(),
        {'model': 'artwork.artwork'},
        name='artwork-view'),
    url(r'^artwork(?P<pk>\d+).pde$', redirect.views.ObjectRedirectView.as_view(),
        {'model': 'artwork.artwork'},
        name='artwork-code'),
    url(r'^artwork/render/(?P<pk>\d+)/$', redirect.views.ObjectRedirectView.as_view(),
        {'model': 'artwork.artwork'},
        name='artwork-render'),
    url(r'^artwork/render/$', redirect.views.PathRedirectView.as_view(),
        name='artwork-render-create'),
    url(r'^artwork/submit/(?P<pk>\d+)/$', redirect.views.ObjectRedirectView.as_view(),
        {'model': 'artwork.artwork'},
        name='artwork-submit'),

    url(r'^e/?$', redirect.views.PathRedirectView.as_view(),
        name='exhibition-list'),
    url(r'^e/(?P<pk>\d+)/score/$', redirect.views.ObjectRedirectView.as_view(),
        {'model': 'exhibitions.exhibition'},
        name='exhibition-view-score'),
    url(r'^e/list/(?P<pk_list>[\d,]+)?/?$', redirect.views.ObjectRedirectView.as_view(),
        {'model': 'exhibitions.exhibition'},
        name='exhibition-list'),
    url(r'^e/(?P<pk>\d+)/$', redirect.views.ObjectRedirectView.as_view(),
        {'model': 'exhibitions.exhibition'},
        name='exhibition-view'),
    url(r'^exhibition/new/$', redirect.views.PathRedirectView.as_view(),
        name='exhibition-add'),
    url(r'^exhibition/edit/(?P<pk>\d+)/$', redirect.views.ObjectRedirectView.as_view(),
        {'model': 'exhibitions.exhibition'},
        name='exhibition-edit'),
    url(r'^exhibition/delete/(?P<pk>\d+)/$', redirect.views.ObjectRedirectView.as_view(),
        {'model': 'exhibitions.exhibition'},
        name='exhibition-delete'),

    url(r'^s/(?P<pk>\d+)/$', redirect.views.ObjectRedirectView.as_view(),
        {'model': 'submissions.submission'},
        name='submission-view'),
    url(r'^submission/delete/(?P<pk>\d+)/$', redirect.views.ObjectRedirectView.as_view(),
        {'model': 'submissions.submission'},
        name='submission-delete'),

    url(r'^.*/$', redirect.views.WildcardRedirectView.as_view(),
        {'redirect_to': 'home'},
        name='wildcard'),
]
