# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 23:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lti', '0006_cohort_is_default'),
        ('exhibitions', '0003_auto_20150218_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='cohort',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='lti.Cohort'),
        ),
    ]
